#!/usr/bin/env bash
# Writes THIRD-PARTY-NOTICES.txt, and Sources/ThirdPartyNotices.swift which puts
# the same text into the binary (the menu's "Third-Party Licenses..." shows it).
#
#   scripts/generate-third-party-notices.sh           # rewrite both files
#   scripts/generate-third-party-notices.sh --check   # exit 1 if they are stale
#
# The app is compiled from Sources/*.swift with swiftc alone and links only
# Apple's frameworks, which are part of macOS and not shipped in the .app. So
# there is nothing third-party to list, and the notices say so. What this script
# guards is that statement: it fails, instead of writing "no libraries", when
# the repository gains a way to pull code in (Package.swift / Package.resolved /
# an Xcode project) or a source file imports a module that is not an Apple
# framework. When that happens, the notices have to list the new library, and
# this script has to learn to write it.
#
# Runs on Linux and macOS (bash and coreutils only); the PR's test job runs it
# with --check.
set -euo pipefail

cd "$(dirname "$0")/.."

CHECK=0
case "${1:-}" in
  "") ;;
  --check) CHECK=1 ;;
  *)
    echo "Usage: scripts/generate-third-party-notices.sh [--check]" >&2
    exit 1
    ;;
esac

OUT_TXT="THIRD-PARTY-NOTICES.txt"
OUT_SWIFT="Sources/ThirdPartyNotices.swift"

# Modules that come with macOS. Anything else imported by Sources/*.swift is
# assumed to be a library that ends up in the binary.
SYSTEM_MODULES=" AppKit Cocoa Combine CoreGraphics Darwin Dispatch Foundation os QuartzCore Swift SwiftUI WebKit "

# Anywhere in the tree, not only at the root: a nested project (macos/App.xcodeproj
# or a local package) would bring its dependencies in just the same.
FOUND=$(find . \( -path ./.git -o -path ./dist \) -prune -o \
  \( -name Package.swift -o -name Package.resolved -o -name '*.xcodeproj' -o -name '*.xcworkspace' \) \
  -print)
if [ -n "$FOUND" ]; then
  echo "Error: the app may have package dependencies; found:" >&2
  echo "$FOUND" >&2
  echo "List them in the notices and update this script." >&2
  exit 1
fi

# Fails closed: a line that looks like an import declaration but cannot be read
# is an error, not something to skip. The declaration has to take the whole line
# (bar a // comment), so `import Cocoa; import X` is rejected rather than read
# as Cocoa alone.
IMPORT_PREFIX='^[[:space:]]*((@[A-Za-z_][A-Za-z0-9_]*(\([^)]*\))?|public|package|internal|fileprivate|private)[[:space:]]+)*import[[:space:]]'
IMPORT_DECL="${IMPORT_PREFIX}"'+((typealias|struct|class|enum|protocol|let|var|func)[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)(\.[A-Za-z_][A-Za-z0-9_]*)*[[:space:]]*(//.*)?$'
for src in Sources/*.swift; do
  [ "$src" = "$OUT_SWIFT" ] && continue
  # Candidates: every line starting with an attribute, an access modifier or
  # `import` that has the word import in it, e.g. `import X`, `public import X`,
  # `@_spi(Testing) import X`, `import struct X.Y`.
  while IFS= read -r line; do
    module=$(printf '%s\n' "$line" | sed -nE "s#${IMPORT_DECL}#\\6#p")
    if [ -z "$module" ]; then
      echo "Error: $src: cannot read this import declaration: $line" >&2
      exit 1
    fi
    if [[ "$SYSTEM_MODULES" != *" $module "* ]]; then
      echo "Error: $src imports '$module', which is not a known Apple framework." >&2
      echo "If it is one, add it to SYSTEM_MODULES; if not, list it in the notices." >&2
      exit 1
    fi
  done < <(grep -E '^[[:space:]]*(@|public|package|internal|fileprivate|private|import)' "$src" \
             | grep -E '(^|[^A-Za-z0-9_])import([^A-Za-z0-9_]|$)' || true)
done

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

cat > "$TMP_DIR/txt" <<'TEXT'
THIRD-PARTY NOTICES

AmbientBGM Menubar does not bundle any third-party libraries. It is built from
its own Swift sources and uses only the frameworks that come with macOS
(AppKit / Cocoa and WebKit), which are part of the operating system and are not
included in the app.

The music player shown in the app is the web page https://ambientbgm.com,
loaded over the network; it is not part of the app.

Generated by scripts/generate-third-party-notices.sh; do not edit by hand.
TEXT

# A raw string literal (#"""..."""#): backslashes and quotes in the text are
# taken as they are. Only the closing delimiter itself would break it.
if grep -qF '"""#' "$TMP_DIR/txt"; then
  echo "Error: the notices contain '\"\"\"#', which ends the Swift string literal." >&2
  exit 1
fi
{
  echo '// ThirdPartyNotices.swift - generated by scripts/generate-third-party-notices.sh'
  echo '// from THIRD-PARTY-NOTICES.txt. Do not edit by hand.'
  echo ''
  echo 'let thirdPartyNotices = #"""'
  cat "$TMP_DIR/txt"
  echo '"""#'
} > "$TMP_DIR/swift"

if [ "$CHECK" = 1 ]; then
  stale=0
  for pair in "txt:$OUT_TXT" "swift:$OUT_SWIFT"; do
    tmp="$TMP_DIR/${pair%%:*}"
    out="${pair#*:}"
    if [ ! -f "$out" ] || ! diff -u "$out" "$tmp"; then
      echo "Error: $out is out of date. Run scripts/generate-third-party-notices.sh and commit." >&2
      stale=1
    fi
  done
  exit "$stale"
fi

# Moved into place from the same directory, so an interrupted run never leaves a
# half-written file (a mv across file systems is a copy).
cp "$TMP_DIR/txt" "$OUT_TXT.tmp"
mv "$OUT_TXT.tmp" "$OUT_TXT"
cp "$TMP_DIR/swift" "$OUT_SWIFT.tmp"
mv "$OUT_SWIFT.tmp" "$OUT_SWIFT"
echo "Wrote $OUT_TXT and $OUT_SWIFT"
